# Generated by Django 6.0.5 on 2026-08-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liga', models.ImageField(upload_to='media')),
                ('narxi', models.IntegerField()),
                ('namc', models.CharField(max_length=200)),
                ('tavk', models.CharField(max_length=200)),
                ('namr', models.CharField(max_length=200)),
                ('tavt', models.CharField(max_length=200)),
            ],
        ),
    ]
