# Generated by Django 6.0.5 on 2026-08-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kot',
            new_name='Kit',
        ),
    ]
