# Generated by Django 6.0.5 on 2026-08-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzum', '0002_rename_kot_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='narxi1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
