# Generated by Django 6.0.5 on 2026-08-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzum', '0003_kit_narxi1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='namc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='namr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='narxi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='narxi1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='tavk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='tavt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
