# Generated by Django 6.0.5 on 2026-08-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzum', '0004_alter_kit_namc_alter_kit_namr_alter_kit_narxi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
    ]
