# Generated by Django 6.0.5 on 2026-08-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzum', '0005_kit_aktiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='ligb',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kit',
            name='lige',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kit',
            name='ligq',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kit',
            name='ligv',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
